name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build
